# Generated by Django 2.1.2 on 2019-03-30 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_created=True, blank=True, null=True)),
                ('codigo', models.CharField(help_text='El código debe ser numérico', max_length=45)),
                ('nombre', models.CharField(max_length=45)),
                ('tipo', models.CharField(choices=[('semillero', 'Semillero'), ('grado', 'Grado')], max_length=45)),
                ('integrantes', models.ManyToManyField(to='integrantes.Integrante')),
                ('lider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='integrantes.Integrante')),
            ],
        ),
    ]
