# Generated by Django 2.2 on 2019-04-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_creacion',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='integrantes',
            field=models.ManyToManyField(blank=True, to='integrantes.Integrante'),
        ),
    ]
