# Generated by Django 2.1.7 on 2019-04-27 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_merge_20190416_0054'),
        ('proyectos', '0003_merge_20190415_1213'),
    ]

    operations = [
    ]
