# Generated by Django 2.1.7 on 2019-05-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_merge_20190427_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='foto_proyectos/'),
        ),
    ]
