# Generated by Django 2.2 on 2019-09-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_proyecto_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='prueba',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
    ]
