# Generated by Django 2.2 on 2019-09-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0006_proyecto_prueba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='prueba',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='descripcion',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
