# Generated by Django 2.2 on 2019-09-17 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0007_auto_20190916_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='descripcion',
        ),
    ]
