# Generated by Django 2.2 on 2019-10-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0008_remove_proyecto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='foto_proyectos'),
        ),
    ]
