# Generated by Django 2.2 on 2020-02-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0009_auto_20191018_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='descripcion',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
    ]
