# Generated by Django 2.2 on 2019-10-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_auto_20190518_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografias',
            name='fotos',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
