# Generated by Django 2.2 on 2019-04-05 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrantes', '0002_auto_20190405_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semillero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=45)),
                ('nombre', models.CharField(max_length=45)),
                ('programa', models.CharField(max_length=45)),
                ('fecha_creacion', models.DateField(auto_now=True, null=True)),
                ('integrantes', models.ManyToManyField(blank=True, to='integrantes.Integrante')),
                ('lider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Semillero', to='integrantes.Integrante')),
            ],
        ),
    ]
