# Generated by Django 2.1.2 on 2019-03-30 16:15

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('identificacion', models.CharField(max_length=45)),
                ('sexo', models.CharField(max_length=1)),
                ('fecha_nacimiento', models.DateTimeField()),
                ('telefono', models.CharField(blank=True, max_length=12, null=True)),
                ('direccion', models.CharField(blank=True, max_length=45, null=True)),
                ('programa', models.CharField(choices=[('ing_sistemas', 'Ingenieria de Sistemas'), ('ing_telecomunicaciones', 'Ingenieria de Telecomunicaciones'), ('ing_industrial', 'Ingenieria de Industrial')], max_length=45)),
                ('ciudad', models.CharField(max_length=45)),
                ('centro', models.CharField(max_length=45)),
                ('foto', models.FileField(blank=True, null=True, upload_to='foto_integrante/')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
