# Generated by Django 2.1.7 on 2019-04-16 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrantes', '0002_auto_20190405_0019'),
        ('integrantes', '0002_auto_20190406_1624'),
    ]

    operations = [
    ]
