# Generated by Django 2.2 on 2019-10-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrantes', '0004_merge_20190427_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrante',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
