# Generated by Django 2.2 on 2019-10-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrantes', '0005_auto_20191018_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrante',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='foto_integrante'),
        ),
    ]
